services:
  db:
    image: postgres:15
    container_name: nextjs-exam
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Test1234
      POSTGRES_DB: nextExamDb
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

# version: '3.8'

# services:
#   postgres:
#     image: postgres:15
#     container_name: examNext
#     environment:
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: secret123
#       POSTGRES_DB: exam
#       POSTGRES_HOST_AUTH_METHOD: md5
#     ports:
#       - "5433:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#     networks:
#       - db-network

#   pgadmin:
#     image: dpage/pgadmin4:7.8
#     container_name: my-pgadmin
#     environment:
#       PGADMIN_DEFAULT_EMAIL: nextjs@exam.com
#       PGADMIN_DEFAULT_PASSWORD: secret123
#     ports:
#       - "8081:80"
#     volumes:
#       - pgadmin_data:/var/lib/pgadmin
#     networks:
#       - db-network
#     depends_on:
#       - postgres

# volumes:
#   postgres_data:
#   pgadmin_data:

# networks:
#   db-network: